### ISSUE TITLE
Auth Logic Container Component or Higher Order Function

### ISSUE THREAD

**Issue by johnlindquist** [eggheadio/egghead-io-nextjs#13]
`getServerSideProps` for auth needs to be shared across many components. Having it contained in a single place (a container or high order function) will solve that problem before it becomes an issue.

Here's some research we need to dive into (I haven't read/grokked this yet):
https://github.com/vercel/next.js/discussions/10925

**Comment by joelhooks** [comment]
One of the things that we discussed was the idea that we might not need this level of auth for this application because **most** of the data we display is public and we are only protecting small amounts versus SaaS apps etc that have a lot of auth'd data.

**Comment by joelhooks** [comment]
This is more relevant if we are working with an auth'd dashboard/profile or similar. 

I actually got the cookie reading server side auth working and the HOC approach in that link is straight forward enough.

**Comment by johnlindquist** [comment]
Cool, cool. Maybe someday when "Enterprise Features" resurfaces it's ugly head we'll circle back to this
