### ISSUE TITLE
Instructors Pagination page # in URL?

### ISSUE THREAD

**Issue by johnlindquist** [eggheadio/egghead-io-nextjs#15]
Current egghead.io behavior: 
- egghead.io/instructors/2 loads Kent's page
- Pagination doesn't change the url

Desired behavior:
- Pagination updates URL to instructors/1 so I can read the "1" from the URL to track the current page

**Comment by joelhooks** [comment]
I'm generally in favor of losing pagination wherever possible. Nobody pages through pages 😬

**Comment by johnlindquist** [comment]
Consider it lost!
