### ISSUE TITLE
Navigation failing when clicking quickly

### ISSUE THREAD

**Issue by johnlindquist** [eggheadio/egghead-io-nextjs#21]
I'm noticing in my dev environment that if I quickly click between links making the graphql calls, sometimes Next.js will hang. I don't know what the issue is, but will investigate.

**Comment by joelhooks** [comment]
Is this still occuring?

**Comment by johnlindquist** [comment]
Yes, but only in local dev environment. I haven't had any luck in finding a solution, I guess Next.js prevents disabling HMR because reasons. Closing.
